// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SynMessage struct {
	Id               *string   `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Origin           *string   `protobuf:"bytes,2,req,name=origin" json:"origin,omitempty"`
	Digests          []*Digest `protobuf:"bytes,3,rep,name=digests" json:"digests,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SynMessage) Reset()         { *m = SynMessage{} }
func (m *SynMessage) String() string { return proto.CompactTextString(m) }
func (*SynMessage) ProtoMessage()    {}

func (m *SynMessage) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *SynMessage) GetOrigin() string {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return ""
}

func (m *SynMessage) GetDigests() []*Digest {
	if m != nil {
		return m.Digests
	}
	return nil
}

type AckMessage struct {
	Id               *string   `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Origin           *string   `protobuf:"bytes,2,req,name=origin" json:"origin,omitempty"`
	Digests          []*Digest `protobuf:"bytes,3,rep,name=digests" json:"digests,omitempty"`
	Deltas           []*Delta  `protobuf:"bytes,4,rep,name=deltas" json:"deltas,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *AckMessage) Reset()         { *m = AckMessage{} }
func (m *AckMessage) String() string { return proto.CompactTextString(m) }
func (*AckMessage) ProtoMessage()    {}

func (m *AckMessage) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *AckMessage) GetOrigin() string {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return ""
}

func (m *AckMessage) GetDigests() []*Digest {
	if m != nil {
		return m.Digests
	}
	return nil
}

func (m *AckMessage) GetDeltas() []*Delta {
	if m != nil {
		return m.Deltas
	}
	return nil
}

type Ack2Message struct {
	Id               *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Origin           *string  `protobuf:"bytes,2,req,name=origin" json:"origin,omitempty"`
	Deltas           []*Delta `protobuf:"bytes,3,rep,name=deltas" json:"deltas,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Ack2Message) Reset()         { *m = Ack2Message{} }
func (m *Ack2Message) String() string { return proto.CompactTextString(m) }
func (*Ack2Message) ProtoMessage()    {}

func (m *Ack2Message) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Ack2Message) GetOrigin() string {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return ""
}

func (m *Ack2Message) GetDeltas() []*Delta {
	if m != nil {
		return m.Deltas
	}
	return nil
}

type Digest struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Gen              *int64  `protobuf:"varint,2,req,name=gen" json:"gen,omitempty"`
	Version          *int64  `protobuf:"varint,3,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Digest) Reset()         { *m = Digest{} }
func (m *Digest) String() string { return proto.CompactTextString(m) }
func (*Digest) ProtoMessage()    {}

func (m *Digest) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Digest) GetGen() int64 {
	if m != nil && m.Gen != nil {
		return *m.Gen
	}
	return 0
}

func (m *Digest) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type Delta struct {
	Id               *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Gen              *int64   `protobuf:"varint,2,req,name=gen" json:"gen,omitempty"`
	Version          *int64   `protobuf:"varint,3,req,name=version" json:"version,omitempty"`
	Heartbeat        *int64   `protobuf:"varint,4,req,name=heartbeat" json:"heartbeat,omitempty"`
	Values           []*Value `protobuf:"bytes,5,rep,name=values" json:"values,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Delta) Reset()         { *m = Delta{} }
func (m *Delta) String() string { return proto.CompactTextString(m) }
func (*Delta) ProtoMessage()    {}

func (m *Delta) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Delta) GetGen() int64 {
	if m != nil && m.Gen != nil {
		return *m.Gen
	}
	return 0
}

func (m *Delta) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Delta) GetHeartbeat() int64 {
	if m != nil && m.Heartbeat != nil {
		return *m.Heartbeat
	}
	return 0
}

func (m *Delta) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type Value struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	Version          *int64  `protobuf:"varint,3,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}

func (m *Value) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Value) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *Value) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func init() {
}
